dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libboost-all-dev

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -D ENABLE_MPI=NO -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . --
  - ctest
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-6
